

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <h2>HEADER</h2>
        {children}
        <h3>FOOTER</h3>
      </body>
    </html>
  );
}
