import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import "../global.scss";
import { Container } from "react-bootstrap";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Header/>
        <Container>{children}</Container>
        <Footer/>
      </body>
    </html>
  );
}
